# Generated by Django 4.1.1 on 2022-09-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_prices',
            new_name='discounted_price',
        ),
    ]
